---
- name: install packages required for avahi-aliases
  package: name={{item}} state=latest update_cache=yes
  with_items:
    - avahi-daemon
    - python-avahi
    - python-pip

- name: install avahi-aliases
  pip: name='git+git://github.com/till/avahi-aliases.git@topics/make-it-run' editable=false
  notify:
    - start avahi-aliases
