---
- name: Find remote_user matching host_uid
  shell: "getent passwd {{ host_uid }} | cut -d: -f1"
  register: remote_user

- set_fact: move_remote_user=true
  when: remote_user.stdout != '' and remote_user.stdout != web_user

- name: Move remote_user out of the way
  user:
    name: "{{ remote_user.stdout }}"
    uid: "{{ alternate_id }}"
  when: move_remote_user

- name: Map web_user to host_uid
  user:
    name: "{{ web_user }}"
    uid: "{{ host_uid }}"

- name: Find remote_group matching host_gid
  shell: "getent group {{ host_gid }} | cut -d: -f1"
  register: remote_group

- set_fact: move_remote_group=true
  when: remote_group.stdout != '' and remote_group.stdout != web_group

- name: Move remote_group out of the way
  group:
    name: "{{ remote_group.stdout }}"
    gid: "{{ alternate_id }}"
  when: move_remote_group

- name: Map web_group to host_gid
  group:
    name: "{{ web_group }}"
    gid: "{{ host_gid }}"
